# Generated by Django 6.0.4 on 2026-05-03 18:46

import app2.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0005_teachingassignment_time_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admindata',
            name='address',
            field=app2.fields.EncryptedCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='admindata',
            name='contact',
            field=app2.fields.EncryptedCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='address',
            field=app2.fields.EncryptedCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='contact',
            field=app2.fields.EncryptedCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='dob',
            field=app2.fields.EncryptedCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='teacherdata',
            name='address',
            field=app2.fields.EncryptedCharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='teacherdata',
            name='dob',
            field=app2.fields.EncryptedDateField(),
        ),
        migrations.AlterField(
            model_name='teacherdata',
            name='phone',
            field=app2.fields.EncryptedCharField(max_length=255),
        ),
    ]
